//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentLogs
    {
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string EventType { get; set; }
        public System.DateTime EventTime { get; set; }
        public string Parameters { get; set; }
        public string Description { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual ProductionBatches ProductionBatches { get; set; }
    }
}
