//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtruderLogs
    {
        public int Id { get; set; }
        public int BatchId { get; set; }
        public int ProgramId { get; set; }
        public System.DateTime LoadedAt { get; set; }
        public int LoadedBy { get; set; }
        public string Parameters { get; set; }
    
        public virtual ProductionBatches ProductionBatches { get; set; }
        public virtual ExtruderPrograms ExtruderPrograms { get; set; }
        public virtual Users Users { get; set; }
    }
}
