//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtruderZones
    {
        public int Id { get; set; }
        public int ProgramId { get; set; }
        public int ZoneNumber { get; set; }
        public string ZoneName { get; set; }
        public decimal TemperatureSetpoint { get; set; }
        public decimal TemperatureMin { get; set; }
        public decimal TemperatureMax { get; set; }
        public decimal PressureSetpoint { get; set; }
        public decimal PressureMin { get; set; }
        public decimal PressureMax { get; set; }
        public int ScrewSpeed { get; set; }
        public int FeedRate { get; set; }
    
        public virtual ExtruderPrograms ExtruderPrograms { get; set; }
    }
}
