//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtruderTelemetry
    {
        public int Id { get; set; }
        public string BatchNumber { get; set; }
        public int ZoneNumber { get; set; }
        public decimal CurrentTemperature { get; set; }
        public decimal CurrentPressure { get; set; }
        public int CurrentSpeed { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Status { get; set; }
    }
}
