//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTestParameters
    {
        public int Id { get; set; }
        public int TestId { get; set; }
        public string ParameterName { get; set; }
        public Nullable<decimal> NormMin { get; set; }
        public Nullable<decimal> NormMax { get; set; }
        public Nullable<decimal> ActualValue { get; set; }
        public string Unit { get; set; }
        public Nullable<bool> IsPassed { get; set; }
    
        public virtual LabTests LabTests { get; set; }
    }
}
