//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialBatches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RawMaterialBatches()
        {
            this.BatchMaterials = new HashSet<BatchMaterials>();
        }
    
        public int Id { get; set; }
        public string BatchNumber { get; set; }
        public string SupplierBatch { get; set; }
        public int MaterialId { get; set; }
        public string Supplier { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public string LabStatus { get; set; }
        public Nullable<System.DateTime> DecisionAt { get; set; }
        public Nullable<int> DecisionBy { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchMaterials> BatchMaterials { get; set; }
        public virtual Users Users { get; set; }
        public virtual RawMaterials RawMaterials { get; set; }
    }
}
