//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeComponents
    {
        public int Id { get; set; }
        public int RecipeId { get; set; }
        public int RawMaterialId { get; set; }
        public decimal Percentage { get; set; }
        public Nullable<decimal> ToleranceMin { get; set; }
        public Nullable<decimal> ToleranceMax { get; set; }
        public int LoadOrder { get; set; }
    
        public virtual RawMaterials RawMaterials { get; set; }
        public virtual Recipes Recipes { get; set; }
    }
}
