//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechSteps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechSteps()
        {
            this.BatchStepExecutions = new HashSet<BatchStepExecutions>();
        }
    
        public int Id { get; set; }
        public int TechCardId { get; set; }
        public int StepNumber { get; set; }
        public string StepType { get; set; }
        public string Name { get; set; }
        public string Instruction { get; set; }
        public bool IsMandatory { get; set; }
        public string PlannedParams { get; set; }
        public string ToleranceParams { get; set; }
        public Nullable<int> EquipmentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchStepExecutions> BatchStepExecutions { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual TechCards TechCards { get; set; }
    }
}
