//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ActiveBatches
    {
        public string BatchNumber { get; set; }
        public string ProductName { get; set; }
        public string Line { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
    }
}
