//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchStepExecutions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatchStepExecutions()
        {
            this.DeviationEvents = new HashSet<DeviationEvents>();
        }
    
        public int Id { get; set; }
        public int BatchId { get; set; }
        public int StepId { get; set; }
        public int StepNumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.DateTime> FinishedAt { get; set; }
        public Nullable<int> StartedBy { get; set; }
        public Nullable<int> FinishedBy { get; set; }
        public string ActualParams { get; set; }
        public Nullable<int> EquipmentId { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationEvents> DeviationEvents { get; set; }
        public virtual ProductionBatches ProductionBatches { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual TechSteps TechSteps { get; set; }
    }
}
