//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviationEvents
    {
        public int Id { get; set; }
        public int BatchId { get; set; }
        public Nullable<int> StepExecutionId { get; set; }
        public string EventType { get; set; }
        public string ParameterName { get; set; }
        public string PlannedValue { get; set; }
        public string ActualValue { get; set; }
        public string Severity { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ResolvedAt { get; set; }
        public Nullable<int> ResolvedBy { get; set; }
        public Nullable<int> EquipmentId { get; set; }
    
        public virtual BatchStepExecutions BatchStepExecutions { get; set; }
        public virtual ProductionBatches ProductionBatches { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
