//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabTests()
        {
            this.LabTestParameters = new HashSet<LabTestParameters>();
        }
    
        public int Id { get; set; }
        public string TestNumber { get; set; }
        public string TestType { get; set; }
        public string ObjectType { get; set; }
        public int ObjectId { get; set; }
        public System.DateTime AssignedAt { get; set; }
        public int AssignedBy { get; set; }
        public Nullable<int> ExecutedBy { get; set; }
        public Nullable<System.DateTime> ExecutedAt { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabTestParameters> LabTestParameters { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
