//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceRecords
    {
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public System.DateTime MaintenanceDate { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> PerformedBy { get; set; }
        public Nullable<System.DateTime> NextMaintenanceDate { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Users Users { get; set; }
    }
}
