//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZR_Production_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionBatches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionBatches()
        {
            this.BatchMaterials = new HashSet<BatchMaterials>();
            this.BatchStepExecutions = new HashSet<BatchStepExecutions>();
            this.DeviationEvents = new HashSet<DeviationEvents>();
            this.EquipmentLogs = new HashSet<EquipmentLogs>();
        }
    
        public int Id { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<int> OrderId { get; set; }
        public int ProductId { get; set; }
        public int RecipeId { get; set; }
        public int TechCardId { get; set; }
        public string Line { get; set; }
        public string Status { get; set; }
        public string LabStatus { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.DateTime> FinishedAt { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> EquipmentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchMaterials> BatchMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchStepExecutions> BatchStepExecutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationEvents> DeviationEvents { get; set; }
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentLogs> EquipmentLogs { get; set; }
        public virtual Users Users { get; set; }
        public virtual ProductionOrders ProductionOrders { get; set; }
        public virtual Products Products { get; set; }
        public virtual Recipes Recipes { get; set; }
        public virtual TechCards TechCards { get; set; }
    }
}
